# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81a2d63e0cd0fe0e9e7c7a7f5fa037d47cc064e56c46ca55f68621cfc50da53a6fb4c769255fad629f1b525415fef743d14415992322b9e20c6bdc9632844c81

test:
  secret_key_base: 0eb0dd928f28848cb8a112d8436217fac1b5ac73cc2755e474f240f90bed7ac0914fe0b79139da4afc0c0b5feec28728f935325d538f97c5d676167c0a57a1b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
